// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as MovieModel from "../../models/MovieModel.js";
import * as UrlQueryParam from "../../routes/UrlQueryParam.js";
import * as React$1 from "@headlessui/react";
import * as Solid from "@heroicons/react/solid";

function string(prim) {
  return prim;
}

function array(prim) {
  return prim;
}

var filter_data = [
  MovieModel.popularity,
  MovieModel.vote_average,
  MovieModel.original_title,
  MovieModel.release_date
];

var selectedRef = {
  contents: MovieModel.popularity
};

function FilterBox(Props) {
  var match = UrlQueryParam.useQueryParams(undefined);
  var setQueryParam = match[1];
  var queryParam = match[0];
  React.useMemo((function () {
          if (queryParam.TAG !== /* Genre */1) {
            return ;
          }
          var sort_by = queryParam._0.sort_by;
          var x = Belt_Array.getBy(filter_data, (function (x) {
                  return x.id === sort_by;
                }));
          if (x !== undefined) {
            selectedRef.contents = x;
            return ;
          }
          
        }), [queryParam]);
  var onChange = function (v) {
    selectedRef.contents = v;
    if (queryParam.TAG !== /* Genre */1) {
      return ;
    }
    var match = queryParam._0;
    Curry._1(setQueryParam, {
          TAG: /* Genre */1,
          _0: {
            id: match.id,
            name: match.name,
            display: match.display,
            page: match.page,
            sort_by: v.id
          }
        });
  };
  return React.createElement("div", {
              className: "w-[8rem] flex items-center justify-center text-base rounded-md text-700 py-1 px-2 outline-none ring-0 hover:bg-300"
            }, React.createElement(React$1.Listbox, {
                  value: selectedRef.contents,
                  onChange: onChange,
                  children: React.createElement("div", {
                        className: "w-full relative flex"
                      }, React.createElement(React$1.Listbox.Button, {
                            className: "flex w-full h-full items-center justify-center cursor-pointer ring-0 outline-none",
                            children: null
                          }, React.createElement("span", {
                                className: "flex m-auto truncate "
                              }, selectedRef.contents.name), React.createElement("div", {
                                className: "ml-auto"
                              }, React.createElement(Solid.ChevronDownIcon, {
                                    className: "w-4 h-4"
                                  }))), React.createElement(React$1.Listbox.Options, {
                            className: "absolute top-[2rem] -left-10 w-[10rem] rounded bg-200 py-1 outline-none ring-0",
                            children: Belt_Array.map(filter_data, (function (item) {
                                    return React.createElement(React$1.Listbox.Option, {
                                                value: item,
                                                className: "flex w-full",
                                                children: (function (param) {
                                                    return React.createElement("div", {
                                                                className: "" + (
                                                                  param.active ? "bg-300" : ""
                                                                ) + " flex w-full pl-2 items-center p-[1px]"
                                                              }, param.selected ? React.createElement(Solid.CheckIcon, {
                                                                      className: "h-6 w-6 fill-klor-500"
                                                                    }) : React.createElement("span", {
                                                                      className: "block h-6 w-6"
                                                                    }), React.createElement("span", {
                                                                    className: " w-full pl-4"
                                                                  }, item.name));
                                                  }),
                                                key: item.id
                                              });
                                  }))
                          }))
                }));
}

var make = FilterBox;

export {
  string ,
  array ,
  filter_data ,
  selectedRef ,
  make ,
}
/* react Not a pure module */
