// Generated by ReScript, PLEASE EDIT WITH CARE


var Button = {};

var Items = {};

var Item = {};

var Menu = {
  Button: Button,
  Items: Items,
  Item: Item
};

var Panel = {};

var Title = {};

var Description = {};

var Overlay = {};

var Dialog = {
  Panel: Panel,
  Title: Title,
  Description: Description,
  Overlay: Overlay
};

var Child = {};

var Transition = {
  Child: Child
};

var Button$1 = {};

var Options = {};

var $$Option = {};

var Listbox = {
  Button: Button$1,
  Options: Options,
  $$Option: $$Option
};

var Group = {};

var List = {};

var Panels = {};

var Panel$1 = {};

var Tab = {
  Group: Group,
  List: List,
  Panels: Panels,
  Panel: Panel$1
};

export {
  Menu ,
  Dialog ,
  Transition ,
  Listbox ,
  Tab ,
}
/* No side effect */
