// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function useTitle(title) {
  var prevTitle = React.useRef(window.document.title);
  React.useEffect((function () {
          window.document.title = title;
          return (function (param) {
                    window.document.title = prevTitle.current;
                  });
        }), [title]);
}

export {
  useTitle ,
}
/* react Not a pure module */
