// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function getMatchMedia(query) {
  return window.matchMedia(query);
}

function matchMedia(query) {
  return window.matchMedia(query).matches;
}

function useMediaQuery(query) {
  var match = React.useState(function () {
        return window.matchMedia(query).matches;
      });
  var setMatches = match[1];
  var handleChange = function (param) {
    Curry._1(setMatches, (function (param) {
            return window.matchMedia(query).matches;
          }));
  };
  React.useEffect((function () {
          Curry._1(setMatches, (function (param) {
                  return window.matchMedia(query).matches;
                }));
          window.addEventListener("resize", handleChange);
          return (function (param) {
                    window.removeEventListener("resize", handleChange);
                  });
        }), [query]);
  return match[0];
}

export {
  getMatchMedia ,
  matchMedia ,
  useMediaQuery ,
}
/* react Not a pure module */
