// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as DomBinding from "../bindings/DomBinding.js";

function useWindowSize(param) {
  var match = React.useState(function () {
        return {
                width: 0,
                height: 0
              };
      });
  var setWindowSize = match[1];
  var handleSize = React.useCallback((function (param) {
          Curry._1(setWindowSize, (function (param) {
                  return {
                          width: DomBinding.getWindowInnerWidth(undefined),
                          height: DomBinding.getWindowInnerHeight(undefined)
                        };
                }));
        }), []);
  React.useEffect((function () {
          window.addEventListener("resize", handleSize);
          return (function (param) {
                    window.removeEventListener("resize", handleSize);
                  });
        }), [handleSize]);
  React.useLayoutEffect((function () {
          Curry._1(setWindowSize, (function (param) {
                  return {
                          width: DomBinding.getWindowInnerWidth(undefined),
                          height: DomBinding.getWindowInnerHeight(undefined)
                        };
                }));
        }), []);
  return match[0];
}

export {
  useWindowSize ,
}
/* react Not a pure module */
