// Generated by ReScript, PLEASE EDIT WITH CARE


var imageBaseUrl = "https://image.tmdb.org/t/p";

function getPosterImageW342Link(seg) {
  return "" + imageBaseUrl + "/w342/" + seg + "";
}

var apiBaseUrl = "https://api.themoviedb.org";

var apiVersion = "3";

var placeholderImage = "/assets/nothing.svg";

export {
  apiBaseUrl ,
  apiVersion ,
  imageBaseUrl ,
  getPosterImageW342Link ,
  placeholderImage ,
}
/* No side effect */
