// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Json$JsonCombinators from "@glennsl/rescript-json-combinators/src/Json.js";

function Make(M) {
  var parse = function (str) {
    var match = Array.from(new URLSearchParams(str).entries())[0];
    return Json$JsonCombinators.decode(Json$JsonCombinators.parseExn(match[0]), M.to);
  };
  var stringfy = function (o) {
    return JSON.stringify(Curry._1(M.from, o));
  };
  return {
          parse: parse,
          stringfy: stringfy
        };
}

export {
  Make ,
}
/* No side effect */
