// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_option from "rescript/lib/es6/js_option.js";
import * as Caml_format from "rescript/lib/es6/caml_format.js";

function getOrEmptyString(x) {
  return Js_option.getWithDefault("", x);
}

function getOrIntZero(x) {
  return Js_option.getWithDefault(0, x);
}

function getOrFloatZero(x) {
  return Js_option.getWithDefault(0, x);
}

function toStringElement(str) {
  return str;
}

function toIntElement(n) {
  return n;
}

function toFloatElement(n) {
  return n;
}

function itos(prim) {
  return prim.toString();
}

function ftos(prim) {
  return prim.toString();
}

var stoi = Caml_format.int_of_string;

var stof = Caml_format.float_of_string;

function isEmptyString(str) {
  return str.length === 0;
}

function isEmptyArray(arr) {
  return arr.length === 0;
}

function toLocaleString(date, monthTypeOpt, param) {
  var monthType = monthTypeOpt !== undefined ? monthTypeOpt : "long";
  if (date === undefined) {
    return "";
  }
  try {
    return new Date(date).toLocaleString("en-GB", {
                day: "numeric",
                month: monthType,
                year: "numeric"
              });
  }
  catch (exn){
    return "";
  }
}

export {
  getOrEmptyString ,
  getOrIntZero ,
  getOrFloatZero ,
  toStringElement ,
  toIntElement ,
  toFloatElement ,
  itos ,
  ftos ,
  stoi ,
  stof ,
  isEmptyString ,
  isEmptyArray ,
  toLocaleString ,
}
/* No side effect */
