// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.js";
import * as Solid from "@heroicons/react/solid";

function string(prim) {
  return prim;
}

function About$AuthorLink(Props) {
  var link = Props.link;
  var site = Props.site;
  var title = Props.title;
  return React.createElement("div", undefined, React.createElement("span", {
                  className: "text-600 font-general"
                }, "" + site + ":"), React.createElement("a", {
                  className: "hover:cursor-pointer hover:text-600 text-400 pl-2",
                  href: link,
                  target: "blank"
                }, title));
}

var AuthorLink = {
  make: About$AuthorLink
};

function About$Bioscopes(Props) {
  var onClick = function (e) {
    e.preventDefault();
    RescriptReactRouter.push("/");
  };
  return React.createElement("div", {
              className: "text-base sm:text-xl md:text-2xl font-extrabold bg-gradient-to-r from-klor-400 via-klor-500 to-klor-400 text-yellow-200 flex items-center justify-start gap-2 py-[0.2rem] px-[0.6rem] rounded-full shadow-md shadow-klor-300",
              role: "button",
              onClick: onClick
            }, React.createElement(Solid.CameraIcon, {
                  className: "h-3 w-3 pl-1"
                }), "BIOSCOPES", React.createElement(Solid.CameraIcon, {
                  className: "h-3 w-3 pr-1"
                }));
}

var Bioscopes = {
  make: About$Bioscopes
};

function About(Props) {
  return React.createElement("div", {
              className: "flex flex-col gap-2 text-600 font-sans text-center w-full h-screen items-center justify-center dark:text-slate-100"
            }, React.createElement("div", {
                  className: "flex flex-col items-center justify-center -mt-40"
                }, React.createElement(About$Bioscopes, {}), React.createElement("div", {
                      className: "flex flex-col gap-4 items-center justify-center md:text-2xl font-bold pt-4"
                    }, React.createElement("span", undefined, "Built in ", React.createElement("a", {
                              className: "underline text-red-500 font-brand",
                              href: "https://rescript-lang.org/",
                              rel: "noopener",
                              target: "_blank"
                            }, "ReScript")), React.createElement("span", undefined, "Data provided by ", React.createElement("a", {
                              className: "underline font-brand",
                              href: "https://www.themoviedb.org/",
                              rel: "noopener",
                              target: "_blank"
                            }, "TMDB"))), React.createElement("div", {
                      className: "pt-4"
                    }, React.createElement("a", {
                          className: "text-800 underline text-xl md:text:xl text-center inline font-sans font-semibold",
                          href: "https://github.com/nyinyithann/rescript-react-webpack-tailwind-template",
                          rel: "noreferrer",
                          target: "_blank"
                        }, "GitHub Repo")), React.createElement("div", {
                      className: "pt-2 text-base"
                    }, React.createElement("div", {
                          className: "flex flex-col justify-center items-center font-normal  mt-4 pt-2 border-t border-200 dark:border-slate-400"
                        }, React.createElement("div", {
                              className: "w-24 h-24 relative"
                            }, React.createElement("img", {
                                  className: "w-full h-full rounded-full border-4 border-300",
                                  alt: "mygithub",
                                  src: "https://avatars.githubusercontent.com/u/156037"
                                }), React.createElement("span", {
                                  className: "bg-900 rounded-full text-xs text-200 p-1 absolute right-1 -top-1 border-2 border-300 dark:bg-slate-500 dark:text-white"
                                }, "By")), React.createElement(About$AuthorLink, {
                              link: "https://github.com/nyinyithann",
                              site: "GitHub",
                              title: "@nyinyithann"
                            }), React.createElement(About$AuthorLink, {
                              link: "https://www.linkedin.com/in/nyinyithan/",
                              site: "LinkedIn",
                              title: "@nyinyithann"
                            }), React.createElement(About$AuthorLink, {
                              link: "https://twitter.com/JazzTuyat",
                              site: "Twitter",
                              title: "@JazzTuyat"
                            })))));
}

var make = About;

export {
  string ,
  AuthorLink ,
  Bioscopes ,
  make ,
}
/* react Not a pure module */
