// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as SearchBox from "../components/SearchBox.js";
import * as ThemeMenu from "../components/ThemeMenu.js";
import * as Js_promise from "rescript/lib/es6/js_promise.js";
import * as GithubButton from "../components/GithubButton.js";
import * as SuspensionLoader from "../components/SuspensionLoader.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.js";
import * as Solid from "@heroicons/react/solid";

function string(prim) {
  return prim;
}

var lazyMovieList = React.createElement(React.lazy(function (param) {
          var __x = import("../components/MovieList.js");
          return Js_promise.then_((function (comp) {
                        return Promise.resolve({
                                    default: comp.make
                                  });
                      }), __x);
        }), undefined);

var lazyMovie = React.createElement(React.lazy(function (param) {
          var __x = import("../components/detail_movie/Movie.js");
          return Js_promise.then_((function (comp) {
                        return Promise.resolve({
                                    default: comp.make
                                  });
                      }), __x);
        }), undefined);

var lazyPerson = React.createElement(React.lazy(function (param) {
          var __x = import("../components/Person.js");
          return Js_promise.then_((function (comp) {
                        return Promise.resolve({
                                    default: comp.make
                                  });
                      }), __x);
        }), undefined);

function Home$Bioscopes(Props) {
  var onClick = function (e) {
    e.preventDefault();
    RescriptReactRouter.push("/about");
  };
  return React.createElement("div", {
              className: "text-base sm:text-lg md:text-xl w-full font-extrabold bg-gradient-to-r from-teal-400 via-indigo-400 to-blue-400 text-yellow-200 flex items-center justify-start gap-2 py-[0.2rem] px-[0.6rem] rounded-full shadow-md shadow-klor-300",
              role: "button",
              onClick: onClick
            }, React.createElement(Solid.CameraIcon, {
                  className: "h-3 w-3 pl-1"
                }), "BIOSCOPES", React.createElement(Solid.CameraIcon, {
                  className: "h-3 w-3 pr-1"
                }));
}

var Bioscopes = {
  make: Home$Bioscopes
};

function Home(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var component;
  var exit = 0;
  if (match) {
    var exit$1 = 0;
    switch (match.hd) {
      case "movie" :
          if (match.tl) {
            exit = 1;
          } else {
            component = React.createElement(SuspensionLoader.make, {
                  children: lazyMovie
                });
          }
          break;
      case "person" :
          if (match.tl) {
            exit = 1;
          } else {
            component = React.createElement(SuspensionLoader.make, {
                  children: lazyPerson
                });
          }
          break;
      case "genre" :
      case "search" :
          exit$1 = 2;
          break;
      default:
        exit = 1;
    }
    if (exit$1 === 2) {
      if (match.tl) {
        exit = 1;
      } else {
        component = React.createElement(SuspensionLoader.make, {
              children: lazyMovieList
            });
      }
    }
    
  } else {
    component = React.createElement(SuspensionLoader.make, {
          children: lazyMovieList
        });
  }
  if (exit === 1) {
    component = React.createElement("div", undefined, "Todo: To create a proper component to display message");
  }
  return React.createElement("div", {
              className: "flex flex-col w-full h-full"
            }, React.createElement("div", {
                  className: "h-auto flex flex-col z-50"
                }, React.createElement("div", {
                      className: "flex w-full bg-white sticky top-0 z-50 h-14 flex-shrink-0",
                      id: "navbar"
                    }, React.createElement("div", {
                          className: "hidden sm:flex pl-4 m-auto pr-4"
                        }, React.createElement(Home$Bioscopes, {})), React.createElement("div", {
                          className: "flex flex-1 pl-4 items-center justify-between sm:justify-end gap-2",
                          id: "search-colorswatch-container"
                        }, React.createElement(SearchBox.make, {}), React.createElement("div", {
                              className: "pr-4 place-items-start flex items-center gap-2 z-[50]",
                              id: "colorswatch-container"
                            }, React.createElement(ThemeMenu.make, {}), React.createElement(GithubButton.make, {})))), React.createElement("div", {
                      className: "z-30 bg-white"
                    }, component), React.createElement("footer", {
                      className: "h-8"
                    })));
}

var make = Home;

export {
  string ,
  lazyMovieList ,
  lazyMovie ,
  lazyPerson ,
  Bioscopes ,
  make ,
}
/* lazyMovieList Not a pure module */
