// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Loading from "./Loading.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import ReactLazyLoad from "react-lazy-load";

function LazyImageLite(Props) {
  var className = Props.className;
  var placeholderPath = Props.placeholderPath;
  var alt = Props.alt;
  var src = Props.src;
  var lazyHeight = Props.lazyHeight;
  var lazyOffset = Props.lazyOffset;
  var match = React.useState(function () {
        return false;
      });
  var setLoaded = match[1];
  var lh = (lazyHeight / 2).toString() + "px";
  var tmp = {
    src: src,
    onError: (function (e) {
        if (e.target.src !== placeholderPath) {
          e.target.src = placeholderPath;
          return ;
        }
        
      }),
    onLoad: (function (param) {
        Curry._1(setLoaded, (function (param) {
                return true;
              }));
      })
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  if (alt !== undefined) {
    tmp.alt = Caml_option.valFromOption(alt);
  }
  return React.createElement("div", {
              className: "flex relative items-center justify-center"
            }, match[0] ? null : React.createElement("div", {
                    className: "absolute top-[" + lh + "] w-full h-full flex flex-col items-center justify-center animate-pulse bg-50"
                  }, React.createElement(Loading.make, {
                        className: "w-[8rem] h-[5rem] stroke-[0.2rem] p-3 stroke-klor-200 text-700 dark:fill-slate-600 dark:stroke-slate-400 dark:text-900"
                      })), React.createElement(ReactLazyLoad, {
                  children: React.createElement("img", tmp),
                  offset: lazyOffset,
                  height: lazyHeight
                }));
}

var make = LazyImageLite;

export {
  make ,
}
/* react Not a pure module */
