// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Loading from "./Loading.js";
import * as ModalDialog from "./ModalDialog.js";

function LoadingDialog(Props) {
  var isOpen = Props.isOpen;
  var onClose = Props.onClose;
  return React.createElement(ModalDialog.make, {
              isOpen: isOpen,
              onClose: onClose,
              className: "z-50 relative",
              panelClassName: "w-full h-full rounded",
              opacity: 20,
              children: React.createElement("div", {
                    className: "flex items-center h-8 px-2 rounded-full"
                  }, React.createElement(Loading.make, {
                        className: "w-[6rem] h-[3rem] stroke-[4px] p-[6px] stroke-slate-300 text-slate-600 dark:fill-slate-600 dark:stroke-slate-400 dark:text-900 m-auto"
                      }))
            });
}

var make = LoadingDialog;

export {
  make ,
}
/* react Not a pure module */
