// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_option from "rescript/lib/es6/js_option.js";

function string(prim) {
  return prim;
}

function Movie(Props) {
  var id = Props.id;
  return React.createElement("div", undefined, "Movie " + Js_option.getExn(id));
}

var make = Movie;

export {
  string ,
  make ,
}
/* react Not a pure module */
