// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Links from "../shared/Links.js";
import * as React from "react";
import * as Loading from "./Loading.js";
import * as Js_option from "rescript/lib/es6/js_option.js";
import * as DomBinding from "../bindings/DomBinding.js";
import * as ErrorDisplay from "./ErrorDisplay.js";
import * as MoviesProvider from "../providers/MoviesProvider.js";

function Movie$Hero(Props) {
  var movie = Props.movie;
  var imgPath = Links.getHeroImage(Js_option.getWithDefault("", movie.poster_path));
  var match = React.useState(function () {
        return false;
      });
  var setLoaded = match[1];
  var match$1 = React.useState(function () {
        return false;
      });
  var setErr = match$1[1];
  return React.createElement("div", {
              className: "flex relative"
            }, match[0] ? null : React.createElement("div", {
                    className: "absolute top-[20rem] w-full h-full flex flex-col items-center justify-center animate-pulse bg-50"
                  }, React.createElement(Loading.make, {
                        className: "w-[8rem] h-[5rem] stroke-[0.2rem] p-3 stroke-klor-200 text-700 dark:fill-slate-600 dark:stroke-slate-400 dark:text-900"
                      })), React.createElement("img", {
                  className: "w-full h-[40rem] sm:h-[70rem]",
                  alt: "Poster",
                  src: imgPath,
                  onError: (function (e) {
                      DomBinding.pop("error");
                      Curry._1(setErr, (function (param) {
                              return true;
                            }));
                      if (e.target.src !== Links.placeholderImage) {
                        e.target.src = Links.placeholderImage;
                        return ;
                      }
                      
                    }),
                  onLoad: (function (param) {
                      Curry._1(setLoaded, (function (param) {
                              return true;
                            }));
                    })
                }));
}

var Hero = {
  make: Movie$Hero
};

function string(prim) {
  return prim;
}

function Movie(Props) {
  var id = Props.id;
  var match = MoviesProvider.useMoviesContext(undefined);
  var loadDetailMovie = match.loadDetailMovie;
  var error = match.error;
  var detail_movie = match.detail_movie;
  React.useMemo((function () {
          var t = detail_movie.title;
          if (t !== undefined) {
            window.document.title = t;
          } else {
            window.document.title = "Bioscopes";
          }
        }), [detail_movie]);
  React.useEffect((function () {
          if (id === undefined) {
            return ;
          }
          var controller = new AbortController();
          Curry._2(loadDetailMovie, {
                TAG: /* Movie */3,
                _0: id
              }, controller.signal);
          return (function (param) {
                    controller.abort("Cancel the request");
                  });
        }), []);
  if (error.length > 0) {
    return React.createElement(ErrorDisplay.make, {
                errorMessage: error
              });
  } else if (match.loading) {
    return React.createElement(Loading.make, {
                className: "w-[6rem] h-[3rem] stroke-[0.2rem] p-3 stroke-klor-200 text-green-500 fill-50 dark:fill-slate-600 dark:stroke-slate-400 dark:text-900 m-auto"
              });
  } else {
    return React.createElement("main", {
                className: "flex border-t-[2px] border-slate-200"
              }, React.createElement("div", {
                    className: "flex md:hidden flex-col w-full h-full"
                  }, React.createElement("div", {
                        className: "w-full"
                      }, React.createElement(Movie$Hero, {
                            movie: detail_movie
                          })), React.createElement("div", {
                        className: "w-full bg-green-100 h-40 border-2"
                      })), React.createElement("div", {
                    className: "hidden md:flex w-full h-[80rem]"
                  }, React.createElement("div", {
                        className: "w-2/5 bg-200 border-2"
                      }), React.createElement("div", {
                        className: "w-3/5 bg-green-100 border-2"
                      })));
  }
}

var make = Movie;

export {
  Hero ,
  string ,
  make ,
}
/* react Not a pure module */
