// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Links from "../shared/Links.js";
import * as React from "react";
import * as Js_option from "rescript/lib/es6/js_option.js";
import * as MoviesProvider from "../providers/MoviesProvider.js";

function Movie$Hero(Props) {
  var movie = Props.movie;
  var imgPath = Links.getHeroImage(Js_option.getWithDefault("", movie.poster_path));
  var match = React.useState(function () {
        return false;
      });
  var setLoaded = match[1];
  var match$1 = React.useState(function () {
        return false;
      });
  var setErr = match$1[1];
  return React.createElement("div", {
              className: "flex relative w-full"
            }, React.createElement("img", {
                  className: "w-[24rem] h-[36rem]",
                  alt: "Poster",
                  src: imgPath,
                  onError: (function (e) {
                      Curry._1(setErr, (function (param) {
                              return true;
                            }));
                      if (e.target.src !== Links.placeholderImage) {
                        e.target.src = Links.placeholderImage;
                        return ;
                      }
                      
                    }),
                  onLoad: (function (param) {
                      Curry._1(setLoaded, (function (param) {
                              return true;
                            }));
                    })
                }));
}

var Hero = {
  make: Movie$Hero
};

function string(prim) {
  return prim;
}

function Movie(Props) {
  var id = Props.id;
  var match = MoviesProvider.useMoviesContext(undefined);
  var loadDetailMovie = match.loadDetailMovie;
  var detail_movie = match.detail_movie;
  React.useMemo((function () {
          var t = detail_movie.title;
          if (t !== undefined) {
            window.document.title = t;
          } else {
            window.document.title = "Bioscopes";
          }
        }), [detail_movie]);
  React.useEffect((function () {
          if (id === undefined) {
            return ;
          }
          var controller = new AbortController();
          Curry._2(loadDetailMovie, {
                TAG: /* Movie */3,
                _0: id
              }, controller.signal);
          return (function (param) {
                    controller.abort("Cancel the request");
                  });
        }), []);
  return React.createElement("main", {
              className: "flex p-4 border-t-[2px] border-slate-200"
            }, React.createElement("div", {
                  className: "flex w-full h-[80rem]"
                }, React.createElement("div", {
                      className: "w-[50%] bg-red-500 h-20"
                    }), React.createElement("div", {
                      className: "w-[50%] bg-400 h-20"
                    })));
}

var make = Movie;

export {
  Hero ,
  string ,
  make ,
}
/* react Not a pure module */
