// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as UrlQueryParam from "../routes/UrlQueryParam.js";
import * as Solid from "@heroicons/react/solid";

function SearchBox(Props) {
  var match = UrlQueryParam.useQueryParams(undefined);
  var setQueryParam = match[1];
  var inputRef = React.useRef(null);
  var handleKeyDown = function (e) {
    if (e.key !== "Enter") {
      return ;
    }
    e.preventDefault();
    var elem = inputRef.current;
    if (!(elem == null)) {
      console.log(elem.value);
      return Curry._1(setQueryParam, {
                  TAG: /* Search */2,
                  _0: {
                    query: elem.value,
                    page: 1
                  }
                });
    }
    
  };
  return React.createElement("div", {
              className: "relative w-[12rem] sm:w-[24rem] md:w-[28rem] text-slate-500 focus-within:text-slate-600 flex items-center",
              id: "search-container"
            }, React.createElement("div", {
                  className: "pointer-events-none absolute inset-y-0 left-1 flex items-center"
                }, React.createElement(Solid.SearchIcon, {
                      className: "h-5 w-5"
                    })), React.createElement("input", {
                  ref: inputRef,
                  className: "block w-full rounded-md pl-[2rem] text-gray-900 placeholder-slate-400 outline-none ring-0 border-0 bg-100 focus:bg-200 focus:border-[1px] focus:border-slate-100 focus:placeholder-slate-500 focus:outline-none focus:ring-0 sm:text-sm",
                  id: "search-field",
                  maxLength: 128,
                  name: "search",
                  placeholder: "Search",
                  type: "search",
                  onKeyDown: handleKeyDown
                }));
}

var make = SearchBox;

export {
  make ,
}
/* react Not a pure module */
