// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as UrlQueryParam from "../routes/UrlQueryParam.js";
import * as Solid from "@heroicons/react/solid";

function SearchBox(Props) {
  var match = UrlQueryParam.useQueryParams(undefined);
  var setQueryParam = match[1];
  var queryParam = match[0];
  var inputRef = React.useRef(null);
  React.useEffect((function () {
          if (queryParam.TAG === /* Search */2) {
            var elem = inputRef.current;
            if (!(elem == null)) {
              elem.value = queryParam._0.query;
            }
            
          }
          
        }), [
        queryParam,
        inputRef.current
      ]);
  var handleKeyDown = function (e) {
    if (e.key !== "Enter") {
      return ;
    }
    e.preventDefault();
    var elem = inputRef.current;
    if (!(elem == null)) {
      return Curry._1(setQueryParam, {
                  TAG: /* Search */2,
                  _0: {
                    query: elem.value,
                    page: 1
                  }
                });
    }
    
  };
  var handleChange = function (e) {
    e.preventDefault();
    var v = e.target.value;
    if (v === "") {
      return Curry._1(setQueryParam, {
                  TAG: /* Category */0,
                  _0: {
                    name: "popular",
                    display: "Popular",
                    page: 1
                  }
                });
    }
    
  };
  return React.createElement("div", {
              className: "relative w-[16rem] sm:w-[24rem] md:w-[28rem] text-slate-500 focus-within:text-slate-600 flex items-center",
              id: "search-container"
            }, React.createElement("div", {
                  className: "pointer-events-none absolute inset-y-0 left-1 flex items-center"
                }, React.createElement(Solid.SearchIcon, {
                      className: "h-5 w-5 fill-klor-400"
                    })), React.createElement("input", {
                  ref: inputRef,
                  className: "block w-full rounded-md pl-[2rem] placeholder-klor-400 outline-none ring-0 border-0 bg-200 hover:bg-300 focus:bg-300 focus:border-[1px] focus:border-slate-100 focus:placeholder-slate-500 focus:outline-none focus:ring-0 sm:text-sm text-900",
                  id: "search-field",
                  maxLength: 128,
                  name: "search",
                  placeholder: "Search",
                  type: "search",
                  onKeyDown: handleKeyDown,
                  onChange: handleChange
                }));
}

var make = SearchBox;

export {
  make ,
}
/* react Not a pure module */
