// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util from "../../shared/Util.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Links from "../../shared/Links.js";
import * as React from "react";
import * as Rating from "../Rating.js";
import * as Loading from "../Loading.js";

function string(prim) {
  return prim;
}

function $$int(prim) {
  return prim;
}

function $$float(prim) {
  return prim;
}

function array(prim) {
  return prim;
}

function Hero(Props) {
  var movie = Props.movie;
  var match = React.useState(function () {
        return false;
      });
  var setLoaded = match[1];
  var imgPath = Links.getHeroImage(Util.getOrEmptyString(movie.poster_path));
  var title = Util.getOrEmptyString(movie.title);
  var voteAverage = String(Util.getOrIntZero(movie.vote_count));
  var releaseYear = Util.getOrEmptyString(movie.release_date).substring(0, 4);
  var x = movie.runtime;
  var runtime;
  if (x !== undefined) {
    var t = x | 0;
    runtime = "" + Util.itos(t / 60 | 0) + "h " + Util.itos(t % 60) + "min";
  } else {
    runtime = "";
  }
  return React.createElement("div", {
              className: "flex w-full relative"
            }, match[0] ? null : React.createElement("div", {
                    className: "absolute top-[20rem] w-full h-full flex flex-col items-center justify-center animate-pulse bg-50"
                  }, React.createElement(Loading.make, {
                        className: "w-[8rem] h-[5rem] stroke-[0.2rem] p-3 stroke-klor-200 text-700 dark:fill-slate-600 dark:stroke-slate-400 dark:text-900"
                      })), React.createElement("div", {
                  className: "flex flex-col w-full"
                }, React.createElement("img", {
                      className: "w-full h-[36rem] sm:h-[70rem]",
                      alt: "Poster",
                      src: imgPath,
                      onError: (function (e) {
                          if (e.target.src !== Links.placeholderImage) {
                            e.target.src = Links.placeholderImage;
                            return ;
                          }
                          
                        }),
                      onLoad: (function (param) {
                          Curry._1(setLoaded, (function (param) {
                                  return true;
                                }));
                        })
                    }), React.createElement("div", {
                      className: "flex flex-col w-full p-[0.6rem] gap-2 text-900"
                    }, React.createElement("span", {
                          className: "font-nav text-[2rem]"
                        }, title), React.createElement("div", {
                          className: "flex w-full gap-4"
                        }, React.createElement(Rating.make, {
                              ratingValue: movie.vote_average
                            }), React.createElement("span", undefined, "" + voteAverage + " Reviews")), React.createElement("div", {
                          className: "flex w-full gap-4"
                        }, React.createElement("span", undefined, releaseYear), React.createElement("span", undefined, runtime)))));
}

var make = Hero;

export {
  string ,
  $$int ,
  $$float ,
  array ,
  make ,
}
/* react Not a pure module */
