// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Loading from "../Loading.js";
import * as Js_option from "rescript/lib/es6/js_option.js";
import * as MovieList from "../MovieList.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ErrorDisplay from "../ErrorDisplay.js";
import * as UrlQueryParam from "../../routes/UrlQueryParam.js";
import * as MoviesProvider from "../../providers/MoviesProvider.js";
import * as Solid from "@heroicons/react/solid";

function string(prim) {
  return prim;
}

function array(prim) {
  return prim;
}

function MoreLikeThis(Props) {
  UrlQueryParam.useQueryParams(undefined);
  var match = MoviesProvider.useMoviesContext(undefined);
  var error = match.error;
  var recommendedMovies = match.recommendedMovies;
  var movieList = Js_option.getWithDefault([], recommendedMovies.results);
  var currentPage = Js_option.getWithDefault(0, recommendedMovies.page);
  var totalPages = Js_option.getWithDefault(0, recommendedMovies.total_pages);
  if (error.length > 0) {
    return React.createElement(ErrorDisplay.make, {
                errorMessage: error
              });
  } else if (match.loading) {
    return React.createElement(Loading.make, {
                className: "w-[6rem] h-[3rem] stroke-[0.2rem] p-3 stroke-klor-200 text-green-500 fill-50 dark:fill-slate-600 dark:stroke-slate-400 dark:text-900 m-auto"
              });
  } else {
    return React.createElement("div", {
                className: "flex flex-col bg-white"
              }, React.createElement("div", {
                    className: "w-full h-full flex flex-1 flex-wrap p-1 pt-4 gap-[1rem] sm:gap-[1.4rem] justify-center items-center px-[1rem] sm:px-[2rem] bg-white",
                    id: "movie-list-here"
                  }, movieList.length === 0 ? React.createElement("div", {
                          className: "text-300 text-2xl"
                        }, "Movies Not Found.") : Belt_Array.map(movieList, (function (m) {
                            return React.createElement(MovieList.Poster.make, {
                                        id: m.id.toString(),
                                        media_type: m.media_type,
                                        title: m.title,
                                        poster_path: m.poster_path,
                                        vote_average: m.vote_average,
                                        release_date: m.release_date,
                                        key: m.id.toString()
                                      });
                          }))), React.createElement("div", {
                    className: "flex gap-2 px-4 pt-[2rem]"
                  }, currentPage > 1 ? React.createElement("button", {
                          className: "flex gap-2 px-4 py-2 border-[1px] border-300 bg-300 text-900 rounded hover:bg-400 hover:text-50 group",
                          type: "button",
                          onClick: (function (param) {
                              
                            })
                        }, React.createElement(Solid.ArrowLeftIcon, {
                              className: "h-6 w-6 fill-klor-900 group-hover:fill-klor-50"
                            }), React.createElement("span", undefined, "Page " + (currentPage - 1 | 0).toString() + " ")) : null, currentPage < totalPages ? React.createElement("button", {
                          className: "flex gap-2 px-4 py-2 border-[1px] border-300 bg-300 text-900 rounded hover:bg-400 hover:text-50 group ml-auto",
                          type: "button",
                          onClick: (function (param) {
                              
                            })
                        }, React.createElement("span", undefined, "Page " + (currentPage + 1 | 0).toString() + " "), React.createElement(Solid.ArrowRightIcon, {
                              className: "h-6 w-6 fill-klor-900 group-hover:fill-klor-50"
                            })) : null));
  }
}

var make = MoreLikeThis;

export {
  string ,
  array ,
  make ,
}
/* react Not a pure module */
