// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function NotAvailable(Props) {
  var thing = Props.thing;
  return React.createElement("span", {
              className: "block w-full text-base text-slate-400"
            }, "No " + thing + " available. 😕");
}

var make = NotAvailable;

export {
  make ,
}
/* react Not a pure module */
