// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util from "../../shared/Util.js";
import * as Links from "../../shared/Links.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as NotAvailable from "./NotAvailable.js";
import * as LazyImageLite from "../LazyImageLite.js";

function string(prim) {
  return prim;
}

function $$int(prim) {
  return prim;
}

function $$float(prim) {
  return prim;
}

function array(prim) {
  return prim;
}

function getBackdropImages(movie) {
  return Belt_Option.getWithDefault(Belt_Option.getWithDefault(Belt_Option.map(movie.images, (function (videos) {
                        return videos.backdrops;
                      })), []), []);
}

function getPosterImages(movie) {
  return Belt_Option.getWithDefault(Belt_Option.getWithDefault(Belt_Option.map(movie.images, (function (videos) {
                        return videos.posters;
                      })), []), []);
}

function PhotosPanel$PhotoTitle(Props) {
  var title = Props.title;
  var count = Props.count;
  return React.createElement("div", {
              className: "flex w-full gap-2 items-center font-sans text-900 pb-1"
            }, React.createElement("span", {
                  className: "text-[0.9rem]"
                }, title), React.createElement("span", {
                  className: "text-[0.8rem]"
                }, "" + count.toString() + " " + (
                  count === 1 ? "image" : "images"
                ) + ""));
}

var PhotoTitle = {
  make: PhotosPanel$PhotoTitle
};

function PhotosPanel(Props) {
  var movie = Props.movie;
  var backdrops = getBackdropImages(movie);
  var posters = getPosterImages(movie);
  if (Util.isEmptyArray(backdrops) && Util.isEmptyArray(posters)) {
    return React.createElement(NotAvailable.make, {
                thing: "photos"
              });
  } else {
    return React.createElement("div", {
                className: "flex flex-col w-full gap-8"
              }, Util.isEmptyArray(backdrops) ? null : React.createElement("div", {
                      className: "flex flex-col w-full"
                    }, React.createElement(PhotosPanel$PhotoTitle, {
                          title: "Backdrops",
                          count: backdrops.length
                        }), React.createElement("div", {
                          className: "grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 xl:grid-cols-8 gap-2 justify-center items-center w-full"
                        }, Belt_Array.map(backdrops, (function (bd) {
                                return React.createElement(LazyImageLite.make, {
                                            className: "w-full h-[9.75rem] border-[2px] border-slate-200 rounded-md",
                                            placeholderPath: Links.placeholderImage,
                                            alt: "backdrop image",
                                            src: Links.getPosterImageW533H300Bestv2Link(Util.getOrEmptyString(bd.file_path)),
                                            lazyHeight: 156,
                                            lazyOffset: 50,
                                            key: Util.getOrEmptyString(bd.file_path)
                                          });
                              })))), Util.isEmptyArray(posters) ? null : React.createElement("div", {
                      className: "flex flex-col w-full"
                    }, React.createElement(PhotosPanel$PhotoTitle, {
                          title: "Posters",
                          count: posters.length
                        }), React.createElement("div", {
                          className: "grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 xl:grid-cols-8 gap-2 justify-center items-center w-full"
                        }, Belt_Array.map(posters, (function (bd) {
                                return React.createElement(LazyImageLite.make, {
                                            className: "w-full h-[22rem] border-[2px] border-slate-200 rounded-md",
                                            placeholderPath: Links.placeholderImage,
                                            alt: "poster image",
                                            src: Links.getPosterImage_W370_H556_bestv2Link(Util.getOrEmptyString(bd.file_path)),
                                            lazyHeight: 356,
                                            lazyOffset: 50,
                                            key: Util.getOrEmptyString(bd.file_path)
                                          });
                              })))));
  }
}

var make = PhotosPanel;

export {
  string ,
  $$int ,
  $$float ,
  array ,
  getBackdropImages ,
  getPosterImages ,
  PhotoTitle ,
  make ,
}
/* react Not a pure module */
