// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util from "../../shared/Util.js";
import * as React from "react";

function string(prim) {
  return prim;
}

function $$int(prim) {
  return prim;
}

function $$float(prim) {
  return prim;
}

function array(prim) {
  return prim;
}

function StorylinePanel$Pair(Props) {
  var title = Props.title;
  var value = Props.value;
  return React.createElement("div", {
              className: "flex w-full"
            }, React.createElement("span", {
                  className: "w-1/3 overflow-ellipsis"
                }, Util.toStringElement(title)), React.createElement("span", {
                  className: "w-2/3 overflow-ellipsis"
                }, Util.toStringElement(value)));
}

var Pair = {
  make: StorylinePanel$Pair
};

function StorylinePanel$DirectorLink(Props) {
  return React.createElement(React.Fragment, undefined);
}

var DirectorLink = {
  make: StorylinePanel$DirectorLink
};

function StorylinePanel(Props) {
  var movie = Props.movie;
  var sotryline = Util.toStringElement(Util.getOrEmptyString(movie.overview));
  var x = movie.release_date;
  var releasedDate;
  if (x !== undefined) {
    try {
      releasedDate = new Date(x).toLocaleString("en-GB", {
            day: "numeric",
            month: "long",
            year: "numeric"
          });
    }
    catch (exn){
      releasedDate = "";
    }
  } else {
    releasedDate = "";
  }
  var x$1 = movie.runtime;
  var runtime;
  if (x$1 !== undefined) {
    var t = x$1 | 0;
    runtime = "" + Util.itos(t / 60 | 0) + "h " + Util.itos(t % 60) + "min";
  } else {
    runtime = "";
  }
  return React.createElement("div", {
              className: "flex flex-col w-full"
            }, React.createElement("div", {
                  className: "flex flex-col w-full gap-1"
                }, React.createElement("span", {
                      className: "text-[1.2rem] font-semibold"
                    }, Util.toStringElement("Storyline")), React.createElement("span", {
                      className: "prose break-words"
                    }, sotryline)), React.createElement("div", {
                  className: "flex flex-col w-full prose pt-4"
                }, React.createElement(StorylinePanel$Pair, {
                      title: "Released",
                      value: releasedDate
                    }), React.createElement(StorylinePanel$Pair, {
                      title: "Runtime",
                      value: runtime
                    }), React.createElement(StorylinePanel$DirectorLink, {
                      movie: movie,
                      onClick: (function (param) {
                          
                        })
                    })));
}

var make = StorylinePanel;

export {
  string ,
  $$int ,
  $$float ,
  array ,
  Pair ,
  DirectorLink ,
  make ,
}
/* react Not a pure module */
