// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util from "../../shared/Util.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Links from "../../shared/Links.js";
import * as React from "react";
import * as Loading from "../Loading.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as NotAvailable from "./NotAvailable.js";
import * as Solid from "@heroicons/react/solid";

function string(prim) {
  return prim;
}

function $$int(prim) {
  return prim;
}

function $$float(prim) {
  return prim;
}

function array(prim) {
  return prim;
}

function getVideos(movie) {
  return Belt_Option.getWithDefault(Belt_Option.getWithDefault(Belt_Option.map(movie.videos, (function (videos) {
                        return videos.results;
                      })), []), []);
}

function VideoPanel$VideoImage(Props) {
  var video = Props.video;
  var className = Props.className;
  var match = React.useState(function () {
        return false;
      });
  var setLoaded = match[1];
  var key = Util.getOrEmptyString(video.key);
  return React.createElement(React.Fragment, undefined, Util.isEmptyString(key) ? null : React.createElement(React.Fragment, undefined, match[0] ? null : React.createElement("div", {
                          className: "absolute top-2 w-full h-full flex flex-col items-center justify-center"
                        }, React.createElement(Loading.make, {
                              className: "w-[8rem] h-[5rem] stroke-[0.2rem] p-3 stroke-klor-200 text-700 dark:fill-slate-600 dark:stroke-slate-400 dark:text-900"
                            })), React.createElement("div", {
                        className: "relative flex-inline"
                      }, React.createElement("img", {
                            className: className,
                            alt: "Poster",
                            src: Links.getYoutubeImageLink(key),
                            onError: (function (e) {
                                if (e.target.src !== Links.placeholderImage) {
                                  e.target.src = Links.placeholderImage;
                                  return ;
                                }
                                
                              }),
                            onLoad: (function (param) {
                                Curry._1(setLoaded, (function (param) {
                                        return true;
                                      }));
                              })
                          }), React.createElement("div", {
                            className: "absolute top-0 left-0 bottom-0 right-0 flex items-center justify-center bg-50 bg-opacity-0 sm:bg-opacity-10 hover:bg-opacity-0 hover:cursor-pointer group"
                          }, React.createElement(Solid.PlayIcon, {
                                className: "h-12 w-12 fill-klor-100 stroke-white group-hover:fill-klor-300"
                              })))));
}

var VideoImage = {
  make: VideoPanel$VideoImage
};

function VideoPanel(Props) {
  var movie = Props.movie;
  var videos = getVideos(movie);
  if (Util.isEmptyArray(videos)) {
    return React.createElement(NotAvailable.make, {
                thing: "videos"
              });
  } else {
    return React.createElement("div", {
                className: "grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-6 xl:grid-cols-8 gap-2 justify-center w-full"
              }, Belt_Array.map(videos, (function (video) {
                      return React.createElement(VideoPanel$VideoImage, {
                                  video: video,
                                  className: "w-full border-[2px] border-slate-200 rounded-md\n",
                                  key: Util.getOrEmptyString(video.key)
                                });
                    })));
  }
}

var make = VideoPanel;

export {
  string ,
  $$int ,
  $$float ,
  array ,
  getVideos ,
  VideoImage ,
  make ,
}
/* react Not a pure module */
