// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function string(prim) {
  return prim;
}

function $$int(prim) {
  return prim;
}

function $$float(prim) {
  return prim;
}

function array(prim) {
  return prim;
}

function VideoPanel(Props) {
  return React.createElement("div", undefined);
}

var make = VideoPanel;

export {
  string ,
  $$int ,
  $$float ,
  array ,
  make ,
}
/* react Not a pure module */
