// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util from "../../shared/Util.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as MovieList from "../movie_list/MovieList.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function string(prim) {
  return prim;
}

function array(prim) {
  return prim;
}

function toMovie(cast) {
  return {
          id: Util.getOrIntZero(cast.id),
          poster_path: cast.poster_path,
          release_date: cast.release_date,
          title: cast.title,
          vote_average: cast.vote_average,
          media_type: cast.media_type
        };
}

function KnownFor(Props) {
  var person = Props.person;
  var match = React.useState(function () {
        return [];
      });
  var setMovies = match[1];
  React.useMemo((function () {
          var castList = Belt_Array.keepMap(Belt_Option.getWithDefault(Belt_Option.getWithDefault(Belt_Option.map(person.combined_credits, (function (c) {
                              return Belt_Option.map(c.cast, (function (cc) {
                                            return cc;
                                          }));
                            })), []), []), (function (c) {
                  if (Util.getOrEmptyString(c.media_type) === "movie") {
                    return toMovie(c);
                  }
                  
                }));
          return Curry._1(setMovies, (function (param) {
                        return castList;
                      }));
        }), [person]);
  return React.createElement("div", {
              className: "flex flex-col items-center justify-center bg-white"
            }, React.createElement("ul", {
                  className: "grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 xl:grid-cols-8 gap-y-4 gap-2 justify-center items-start w-full relative"
                }, Belt_Array.map(match[0], (function (movie) {
                        return React.createElement("li", {
                                    key: movie.id.toString() + Util.getOrEmptyString(movie.title)
                                  }, React.createElement(MovieList.Poster.make, {
                                        movie: movie
                                      }));
                      }))));
}

var make = KnownFor;

export {
  string ,
  array ,
  toMovie ,
  make ,
}
/* react Not a pure module */
