// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util from "../../shared/Util.js";
import * as Links from "../../shared/Links.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as PhotosViewer from "../PhotosViewer.js";

function string(prim) {
  return prim;
}

function $$int(prim) {
  return prim;
}

function $$float(prim) {
  return prim;
}

function array(prim) {
  return prim;
}

function PersonPhotos(Props) {
  var person = Props.person;
  var photosRef = React.useRef([]);
  React.useMemo((function () {
          photosRef.current = Belt_Array.keepMap(Belt_Option.getWithDefault(Belt_Option.getWithDefault(Belt_Option.map(person.images, (function (x) {
                              return x.profiles;
                            })), []), []), (function (x) {
                  var filePath = Util.getOrEmptyString(x.file_path);
                  if (filePath !== "") {
                    return {
                            id: filePath,
                            url: Links.getPosterImage_W370_H556_bestv2Link(filePath),
                            type_: "poster"
                          };
                  }
                  
                }));
        }), [person]);
  return React.createElement("div", {
              className: "flex w-full items-center justify-center p-2"
            }, React.createElement(PhotosViewer.make, {
                  photos: photosRef.current
                }));
}

var make = PersonPhotos;

export {
  string ,
  $$int ,
  $$float ,
  array ,
  make ,
}
/* react Not a pure module */
