// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Json$JsonCombinators from "@glennsl/rescript-json-combinators/src/Json.js";
import * as Json_Decode$JsonCombinators from "@glennsl/rescript-json-combinators/src/Json_Decode.js";

var genre = Json_Decode$JsonCombinators.object(function (fields) {
      return {
              id: fields.required("id", Json_Decode$JsonCombinators.$$int),
              name: fields.required("name", Json_Decode$JsonCombinators.string)
            };
    });

var genrelist = Json_Decode$JsonCombinators.object(function (fields) {
      return {
              genres: fields.required("genres", Json_Decode$JsonCombinators.array(genre))
            };
    });

function decode(json) {
  return Json$JsonCombinators.decode(json, genrelist);
}

var GenreDecoder = {
  genre: genre,
  genrelist: genrelist,
  decode: decode
};

var genre_error = Json_Decode$JsonCombinators.object(function (fields) {
      return {
              success: fields.required("success", Json_Decode$JsonCombinators.bool),
              status_code: fields.required("status_code", Json_Decode$JsonCombinators.$$int),
              status_message: fields.required("status_message", Json_Decode$JsonCombinators.string)
            };
    });

function decode$1(json) {
  return Json$JsonCombinators.decode(json, genre_error);
}

var GenreErrorDecoder = {
  genre_error: genre_error,
  decode: decode$1
};

export {
  GenreDecoder ,
  GenreErrorDecoder ,
}
/* genre Not a pure module */
