// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Json$JsonCombinators from "@glennsl/rescript-json-combinators/src/Json.js";
import * as Json_Decode$JsonCombinators from "@glennsl/rescript-json-combinators/src/Json_Decode.js";

var genre = Json_Decode$JsonCombinators.object(function (fields) {
      return {
              id: fields.required("id", Json_Decode$JsonCombinators.$$int),
              name: fields.required("name", Json_Decode$JsonCombinators.string)
            };
    });

var genrelist = Json_Decode$JsonCombinators.object(function (fields) {
      return {
              genres: fields.required("genres", Json_Decode$JsonCombinators.array(genre))
            };
    });

function decode(json) {
  return Json$JsonCombinators.decode(json, genrelist);
}

var GenreDecoder = {
  genre: genre,
  genrelist: genrelist,
  decode: decode
};

export {
  GenreDecoder ,
}
/* genre Not a pure module */
